### ISSUE TITLE
Release v0.2.0-alpha publish list

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#120]
#### Tasks
- [x] https://github.com/blockstack/blockstack-browser/issues/116: clean up browser design file in prep for others to commit designs
- [x] https://github.com/blockstack/blockstack-browser/issues/105: update current example apps to new apps
- [x] https://github.com/blockstack/blockstack-browser/issues/121: app store account creation design
- [x] https://github.com/blockstack/blockstack-browser/issues/75: Install Nucleo font icons and replace icons with fonts
- [x] https://github.com/blockstack/blockstack-browser/issues/117: design new "hello world" app
- [x] https://github.com/blockstack/blockstack-browser/issues/119: blockstack install naming
- [x] https://github.com/blockstack/blockstack-browser/issues/122: Add SSH keys as a key option in the key manager in the profile editor
- [x] https://github.com/blockstack/blockstack-browser/issues/141: Add self-hosting with Dropbox
- [x] https://github.com/blockstack/blockstack-browser/issues/146: CORS proxy breaks account registration
- [x] https://github.com/blockstack/blockstack-browser/issues/150: Polyfill fetch on safari
- [x] https://github.com/blockstack/blockstack-browser/issues/145: A dependency's dependency requires GitHub account
- [x] https://github.com/blockstack/blockstack-browser/issues/98: Re-enable validation of profile tokens (and integrate the new elliptic curve library to do so)

#### Bugs
- [x] https://github.com/blockstack/blockstack-browser/issues/108: Blank email crashes API

**Comment by guylepage3** [comment]
Completed browser portal design

**Comment by guylepage3** [comment]
added "116: clean up browser design file in prep for others to commit designs" to the highlight list.

**Comment by shea256** [comment]
## App Set

### v0.2.0

- Account
- Storage
- Profiles
- Hello, Blockstack

### v0.3.0

- Account
- Storage
- Profiles
- Names
- App Store ("Hello, Blockstack" will be the only app list at first)

**Comment by shea256** [comment]
@guylepage3 I updated the app set above. Can you please take a look?

**Comment by guylepage3** [comment]
@shea256 Nice! I like these names much better than before. They're more intuitive. :)

**Comment by guylepage3** [comment]
Updating the list now..

**Comment by shea256** [comment]
This is all done. Closing this issue out so that we can mark v0.2.0 as complete.
