### ISSUE TITLE
build new browser portal profiles landing view

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#156]
Build new Blockstack Browser Portal Profiles landing view based upon the design from;
- [#155: design new browser portal profiles landing view](https://github.com/blockstack/blockstack-browser/issues/155)

#### Requirements
- [x] app icon
- [x] app details
- [x] search bar
- [x] `<input>` `:hover/:focus` styles
~~- [ ] search dropdown - for this initial build use the current dropdown as is~~
- [x] Personas
~~- [ ] tooltip to see all 37 characters of blockstack id when user hovers over the blockstack id~~
- [x] register button
- [x] mobile testing
- [x] pull navbar search bar inline with navbar items on tablet view
- [x] build out responsive profile cards in column list on tablet view
- [x] tablet testing
- [x] desktop view build
- [x] desktop testing

#### Tasks
- [x] https://github.com/blockstack/blockstack-browser/issues/163: build of new navbar for mobile on profiles landing view
- [x] https://github.com/blockstack/blockstack-browser/issues/180: create new register button for the profiles app landing view
- [x] https://github.com/blockstack/blockstack-browser/issues/177: new profiles app style sheet
- [x] https://github.com/blockstack/blockstack-browser/issues/175: add custom spacing classes to profiles app
- [x] https://github.com/blockstack/blockstack-browser/issues/181: apply new design to personas in profile app landing view
- [x] https://github.com/blockstack/blockstack-browser/issues/191: pull navbar search bar inline with navbar items on tablet view
- [x] https://github.com/blockstack/blockstack-browser/issues/193: build out responsive profile cards in column list on tablet view
- [x] https://github.com/blockstack/blockstack-browser/issues/162: restructure layout of profiles landing view for desktop

#### Bugs
- [x] https://github.com/blockstack/blockstack-browser/issues/190: resolve scrolling issue on profiles app landing mobile view

#### Pushed to next release
- [ ] https://github.com/blockstack/blockstack-browser/issues/176: add search magnifying glass button to profiles app search input
- [ ] https://github.com/blockstack/blockstack-browser/issues/192: resolve looping hover transition on profiles search bar
- [ ] https://github.com/blockstack/blockstack-browser/issues/179: bug: profiles app dropdown not working
- [ ] https://github.com/blockstack/blockstack-browser/issues/189: Profiles app tooltip when hovered over profiles list view

**Comment by guylepage3** [comment]
Noticed that we did not have a search button on the design which is a big UX flaw. Added it to the list.

**Comment by guylepage3** [comment]
Pushing this bug over to next release. https://github.com/blockstack/blockstack-browser/issues/192: resolve looping hover transition on profiles search bar
