### ISSUE TITLE
Resolve input field border issues

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#203]
The text fields are no longer have contrast. They're now white on a white background, so you can't tell where the text fields begins and ends.

<img width="1286" alt="screen shot 2017-02-09 at 5 50 31 pm" src="https://cloud.githubusercontent.com/assets/994646/22806727/7529ae12-eef1-11e6-9b2a-b30dab12c8af.png">

----

#### Tasks
- [x] css usage audit
- [x] identify and change new profiles apps classnames to allow for original input form styles to render
- [x] apply new input parent classname as a temporary fix
- [ ] create new v0.4.0 issue to build new sass architecture for forms
- [ ] create new v0.3.0 issue to apply background gradient to all profile app form pages

**Comment by guylepage3** [comment]
Note to self. 

Resolve by:
- [ ] apply background to the settings app views 
- [ ] apply the gradient background to all profile app views

**Comment by shea256** [comment]
Sounds good @guylepage3.

**Comment by shea256** [comment]
Oh wait, so all of the text fields are going to remain white? Does that mean they won't be compatible with white backgrounds?

**Comment by guylepage3** [comment]
depends upon the app. i plan on changing the backgrounds in some and inputs in others.

**Comment by guylepage3** [comment]
added to the initial comment...

#### Tasks
- [ ] css used audit
- [ ] identify and change new profiles apps classnames to allow for original input form styles to render
- [ ] apply new input parent classname as a temporary fix
- [ ] create new v0.4.0 issue to build new sass architecture for forms
- [ ] create new v0.3.0 issue to apply background gradient to all profile app form pages

**Comment by guylepage3** [comment]
complete
