### ISSUE TITLE
Improve registration prompts

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#210]
- [x] 1. prompt user to connect dropbox if not connected
- [ ] 2. improve readability & placement  pricing and availability status: moved to #232 
- [ ] 3. throttle pricing and availability lookup: The api calls for both of these are very slow to return - we probably want to add a timeout delay and only query if the user has stopped typing for a period of time. moved to #233
- [ ] 4. display error status of registration process see #209

**Comment by shea256** [comment]
I completed #1 and checked off the box above.

I think we should push off #2 and #3.

I'll complete #4 in the morning.

**Comment by guylepage3** [comment]
@larrysalibra @shea256 can we push this to [Release v0.4.0](https://github.com/blockstack/blockstack-browser/milestone/4)?

**Comment by shea256** [comment]
Yes let's push this to 0.4.

**Comment by guylepage3** [comment]
@shea256:

> We should split this issue up into multiple issues.

**Comment by larrysalibra** [comment]
The remaining items are now separate issues: #209 #232 #233
