### ISSUE TITLE
v0.7.0 release overview

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#334]
### Highlights

- n/a

#### Tasks
- [x] https://github.com/blockstack/blockstack-portal/issues/399: macOS: create a logging server
- [x] https://github.com/blockstack/blockstack-portal/issues/400: Write log4js appender compatible with macOS logging server
- [x] https://github.com/blockstack/blockstack-portal/issues/401: Integrate Portal and macOS logging systems
- [x] https://github.com/blockstack/blockstack-portal/issues/378: Figure out how to securely pass Core API password to Portal
- [x] https://github.com/blockstack/blockstack-portal/issues/374: Capture & log JavaScript errors
- [x] https://github.com/blockstack/blockstack-portal/issues/375: Capture macOS logs & errors
- [x] https://github.com/blockstack/blockstack-portal/issues/406: Update README with logging info
- [x] https://github.com/blockstack/blockstack-portal/issues/398: Integrate log4js logging system
- [x] https://github.com/blockstack/blockstack-portal/issues/407: Only enable remote logging if supported
- [x] https://github.com/blockstack/blockstack-portal/issues/402: Add authentication to macOS logging server & portal
- [x] https://github.com/blockstack/blockstack-portal/issues/404: Add useful log events to Portal
- [x] https://github.com/blockstack/blockstack-portal/issues/410: Remove mixpanel code
- [x] https://github.com/blockstack/blockstack-portal/issues/403: macOS: Replace legacy NSLog calls with os_log
- [x] https://github.com/blockstack/blockstack-portal/issues/408: Remove unused legacy Blockstack API code
- [x] https://github.com/blockstack/blockstack-portal/issues/376: Design log aggregation & submission requirements with Core
- [x] https://github.com/blockstack/blockstack-portal/issues/384: Display USD value of BTC in wallet
- [x] https://github.com/blockstack/blockstack-portal/issues/405: Make sure all portal network error conditions are caught & logged
- [x] https://github.com/blockstack/blockstack-portal/issues/229: Version API keys
- [x] https://github.com/blockstack/blockstack-portal/issues/380: get team to install sublime eslint plugin to auto-display lint errors
- [ ] https://github.com/blockstack/blockstack-portal/issues/419: Migrate macOS app to Core sprint branch
- [ ] https://github.com/blockstack/blockstack-portal/issues/420: Make v0.7 build

#### Bugs
- [x] https://github.com/blockstack/blockstack-portal/issues/390: Uncaught TypeError: _blockstack.PrivateKeychain is not a constructor on Account Creation
- [x] https://github.com/blockstack/blockstack-portal/issues/382: resolve bitcoin price issue in the wallet app

#### Pushed to [v0.8.0](https://github.com/blockstack/blockstack-portal/projects/6)
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/391: Round up wallet amount~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/214: design launch modal~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/306: capture the user's email when they set up an account~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/370: create design requirements for the registration process~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/397: Twitter social proof not working~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/320: resolve flexbox flow orientation on home screen~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/388: Cannot read balance preventing access to create profile~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/395: Profile pictures shape~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/389: my portal cannot connect to the blockstack core node~~

**Comment by larrysalibra** [comment]
@guylepage3 can we close this?
