### ISSUE TITLE
v0.8.0 release overview

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#396]
### Highlights

- New backup and recovery process
- Stable name management
- New flow for profile creation
- Improved Blockstack install process

#### Tasks
- [x] https://github.com/blockstack/blockstack-portal/issues/418: Use proxy fetch for pgp keys
- [x] https://github.com/blockstack/blockstack-portal/issues/417: Add sanity checks
- [x] https://github.com/blockstack/blockstack-portal/issues/391: Round up wallet amount
- [x] https://github.com/blockstack/blockstack-portal/pull/443: should be /wallet/receive not /wallet/deposit
- [x] https://github.com/blockstack/blockstack-portal/issues/434: Clean up & write tests for identity store
- [x] https://github.com/blockstack/blockstack-portal/issues/438: Split off pgp store and write tests
- [x] https://github.com/blockstack/blockstack-portal/issues/437: Split off registration store and write tests
- [x] https://github.com/blockstack/blockstack-portal/issues/439: Split off search store and write tests
- [x] https://github.com/blockstack/blockstack-portal/issues/436: Split off & write tests for availability store
- [x] https://github.com/blockstack/blockstack-portal/pull/444: Update README.md for accuracy and clarity
- [ ] https://github.com/blockstack/blockstack-portal/issues/433: Append https to dropbox returned URL
- [ ] https://github.com/blockstack/blockstack-portal/pull/360: v0.6 core auth
- [x] https://github.com/blockstack/blockstack-portal/pull/431: V0.7

#### Bugs
- [x] https://github.com/blockstack/blockstack-portal/issues/429: portal is launching locally on port 3000
- [x] https://github.com/blockstack/blockstack-portal/issues/397: Twitter social proof not working

#### Pushed to v0.9.0
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/377: clean up redux stores~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/435: Re-organize, clean up & write tests for account store~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/430: Can't Register Username~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/383: Process of transferring names from the Onename app~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/88: Add support for updating zone files~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/366: Create a single executable build of Core for macOS~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/379: figure out the quick, gradual on-boarding process~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/306: capture the user's email when they set up an account~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/373: integrate blockstack.js with blockstack-storage~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/389: my portal cannot connect to the blockstack core node~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/371: Backup file design~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/388: Cannot read balance preventing access to create profile~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/370: create design requirements for the registration process~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/372: Update Portal to use new Blockstack UTXO provider~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/262: ui build of edit profile pages inside the profiles app~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/261: design of edit profile pages inside the profiles app~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/214: design launch modal~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/258: live design new profiles app register pages~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/440: Switch to Core 0.14.2~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/423: update portal favicon~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/260: ui build of live search query view inside profiles app~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/259: design live search query view inside profiles app~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/102: allow users to export their backup phrase~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/425: Wallet is not loading a bitcoin address~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/421: Show import name address~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/320: resolve flexbox flow orientation on home screen~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/395: Profile pictures shape~~
