### ISSUE TITLE
v0.9.0 release overview

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#422]
### Highlights
- n/a

#### Tasks
- [x] https://github.com/blockstack/blockstack-browser/issues/480: redesign home screen
- [x] https://github.com/blockstack/blockstack-browser/issues/453: design profile completion bar in status bar
- [x] https://github.com/blockstack/blockstack-browser/issues/484: redesign status bar (based on new home screen status bar)
- [x] https://github.com/blockstack/blockstack-browser/issues/490: Status Bar Documentation v3
- [x] https://github.com/blockstack/blockstack-browser/issues/423: update portal favicon
- [x] https://github.com/blockstack/blockstack-browser/issues/491: ui build of redesigned v3 status bar
- [x] https://github.com/blockstack/blockstack-browser/issues/377: clean up redux stores
- [x] https://github.com/blockstack/blockstack-browser/issues/493: edit DashboardPage.js to HomeScreen.js through out app
- [x] https://github.com/blockstack/blockstack-browser/issues/479: design new profile completion screens
- [x] https://github.com/blockstack/blockstack-browser/issues/435: Re-organize, clean up & write tests for account store
- [x] https://github.com/blockstack/blockstack-browser/issues/430: Can't Register Username
- [x] https://github.com/blockstack/blockstack-browser/issues/483: quick design pass through app icons for consistency
- [x] https://github.com/blockstack/blockstack-browser/issues/306: capture the user's email when they set up an account
- [x] https://github.com/blockstack/blockstack-browser/issues/389: my portal cannot connect to the blockstack core node
- [x] https://github.com/blockstack/blockstack-browser/issues/388: Cannot read balance preventing access to create profile
- [x] https://github.com/blockstack/blockstack-browser/issues/440: Switch to Core 0.14.2
- [x] https://github.com/blockstack/blockstack-browser/issues/102: allow users to export their backup phrase

#### Bugs
- [x] https://github.com/blockstack/blockstack-browser/issues/425: Wallet is not loading a bitcoin address
- [x] https://github.com/blockstack/blockstack-browser/issues/421: Show import name address

#### Duplicate/split
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/489: Implement new status bar, tool tips, etc~~

#### Backlog
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/372: Update Portal to use new Blockstack UTXO provider~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/383: Process of transferring names from the Onename app~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/373: integrate blockstack.js with blockstack-storage~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/366: Create a single executable build of Core for macOS~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/371: Backup file design~~

#### Pushed to [v0.11.0](https://github.com/blockstack/blockstack-portal/projects/9)
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/513: add imagery of browser to readme.md~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/370: create design requirements for the registration process~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/514: design on-boarding screens~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/88: Add support for updating zone files~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/258: live design new profiles app register pages~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/450: build notification banner~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/320: resolve flexbox flow orientation on home screen~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/260: ui build of live search query view inside profiles app~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/262: ui build of edit profile pages inside the profiles app~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/214: design launch modal~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/379: figure out the quick, gradual on-boarding process~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/261: design of edit profile pages inside the profiles app~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/259: design live search query view inside profiles app~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/507: resolve issue with sidebar on storage app~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/488: design installation window~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/466: Review explorer profile card design~~

#### Bugs Pushed to [v0.11.0](https://github.com/blockstack/blockstack-portal/projects/9)
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/395: Profile pictures shape~~
