### ISSUE TITLE
v0.11.0 release overview

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#564]
Blockstack Browser prototype — https://invis.io/N2A7UM1X7

### Highlights
- n/a

#### Tasks
- [x] https://github.com/blockstack/blockstack-browser/issues/563: design a new button for profile creation
- [x] https://github.com/blockstack/blockstack-browser/issues/587: design new status bar with browser utilities
- [x] https://github.com/blockstack/blockstack-browser/issues/586: ui build profiles, storage, wallet, settings apps into status bar to become a browser utilities
- [x] https://github.com/blockstack/blockstack-browser/issues/320: resolve flexbox flow orientation on home screen
- [x] https://github.com/blockstack/blockstack-browser/issues/533: JSON schema file for token file
- [x] https://github.com/blockstack/blockstack-browser/issues/372: Update Portal to use new Blockstack UTXO provider
- [x] https://github.com/blockstack/blockstack-browser/issues/568: add "create a profile" button on profile view screen
- [x] https://github.com/blockstack/blockstack-browser/issues/379: figure out the quick, gradual on-boarding process
- [x] https://github.com/blockstack/blockstack-browser/issues/583: backup profile & account process review
- [x] https://github.com/blockstack/blockstack-browser/issues/549: Wallet displays zero balance until name registration has completed
- [x] https://github.com/blockstack/blockstack-browser/issues/531: Make project work with npm 5
- [x] https://github.com/blockstack/blockstack-browser/issues/596: Add a QR code to the wallet receive tab to support mobile deposits
- [x] https://github.com/blockstack/blockstack-browser/issues/534: Improve on-boarding experience
- [x] https://github.com/blockstack/blockstack-browser/issues/553: Set owner key in core before registration & wallet transfers
- [x] https://github.com/blockstack/blockstack-browser/pull/593: Adding a Create Profile Button
- [x] https://github.com/blockstack/blockstack-browser/pull/591: Adding back buttons
- [x] https://github.com/blockstack/blockstack-browser/pull/601: Can't sign in without username
- [x] https://github.com/blockstack/blockstack-browser/issues/588: node-sass failing with node 8 when trying to setup the project
- [x] https://github.com/blockstack/blockstack-browser/issues/584: restore account & profiles process review (3 user flows)
- [x] https://github.com/blockstack/blockstack-browser/issues/581: Use new search endpoint
- [x] https://github.com/blockstack/blockstack-browser/issues/582: Logging disparity between api_endpoint.log and the macOS log
- [x] https://github.com/blockstack/blockstack-browser/issues/557: full on-boarding/ register a name use case
- [x] https://github.com/blockstack/blockstack-browser/issues/450: build notification banner

#### Bugs
- [x] https://github.com/blockstack/blockstack-browser/issues/556: issue with spacing on home screen
- [x] https://github.com/blockstack/blockstack-browser/issues/560: odd size app icon issues home screen
- [x] https://github.com/blockstack/blockstack-browser/issues/559: change title to read blockstack browser
- [x] https://github.com/blockstack/blockstack-browser/issues/575: unable to view profile after username accepted
- [x] https://github.com/blockstack/blockstack-browser/issues/547: unable to sign in to hello blockstack app
- [x] https://github.com/blockstack/blockstack-browser/issues/567: "+ Create" profile button in profiles app in browser not clickable
- [x] https://github.com/blockstack/blockstack-browser/issues/504: Name registration failed

#### Pushed to [v0.12.0](https://github.com/blockstack/blockstack-portal/projects/10)
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/578: back buttons on on-boarding screens~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/602: update status bar to have navigation controls~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/514: design on-boarding screens~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/570: build new "create profile" button in profiles app~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/569: design update to profile view~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/513: add imagery of browser to readme.md~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/370: create design requirements for the registration process~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/220: update ui of profile card in profile app~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/258: live design new profiles app register pages~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/260: ui build of live search query view inside profiles app~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/262: ui build of edit profile pages inside the profiles app~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/214: design launch modal~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/261: design of edit profile pages inside the profiles app~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/198: create a profile pending view~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/585: pairing screen communications~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/259: design live search query view inside profiles app~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/183: add user's real name to profile card list on landing view~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/573: Social proofs should marked untrusted unless verified~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/507: resolve issue with sidebar on storage app~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/488: design installation window~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/466: Review explorer profile card design~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/554: to do list app icon design~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/458: Address pull request into blockstack app generator~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/589: Add micro-interactions to home screen~~

#### Bugs pushed to [v0.12.0](https://github.com/blockstack/blockstack-portal/projects/10)
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/566: profile list card pending is smaller than non-pending card~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/395: Profile pictures shape~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/494: Profile image won't update when uploaded~~

#### Backlogged
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/366: Create a single executable build of Core for macOS~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/88: Add support for updating zone files~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/562: Migrate state between releases~~
