### ISSUE TITLE
v0.12.0 release overview

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#610]
Blockstack Browser prototype — https://invis.io/N2A7UM1X7

### Highlights
- n/a

#### Tasks
- [x] https://github.com/blockstack/blockstack-browser/issues/578: back buttons on on-boarding screens
- [x] https://github.com/blockstack/blockstack-browser/issues/514: design on-boarding screens
- [x] https://github.com/blockstack/blockstack-browser/issues/624: add guild & ongaku ryoho app icons to home screen
- [x] https://github.com/blockstack/blockstack-browser/issues/515: list the to-do list app on the home screen
- [x] https://github.com/blockstack/blockstack-browser/issues/606: Remove the password
- [x] https://github.com/blockstack/blockstack-browser/issues/554: to do list app icon design
- [x] https://github.com/blockstack/blockstack-browser/issues/569: design update to profile view
- [x] https://github.com/blockstack/blockstack-browser/issues/637: build ui of on-boarding screens
- [x] https://github.com/blockstack/blockstack-browser/issues/634: Update the Status Bar items and design to new design
- [x] https://github.com/blockstack/blockstack-browser/issues/220: update ui of profile card in profile app
- [x] https://github.com/blockstack/blockstack-browser/issues/612: Withdraw only allows integer amounts of bitcoin
- [x] https://github.com/blockstack/blockstack-browser/issues/585: pairing screen communications
- [x] https://github.com/blockstack/blockstack-browser/issues/609: Storage doesn't work without username
- [x] https://github.com/blockstack/blockstack-browser/issues/636: move the storage providers should be at the top within the settings choices
- [x] https://github.com/blockstack/blockstack-browser/issues/534: Improve on-boarding experience
- [x] https://github.com/blockstack/blockstack-browser/issues/632: Auto-generate large profile
- [x] https://github.com/blockstack/blockstack-browser/issues/605: Switch from 24 to 12 word backup phrase
- [x] https://github.com/blockstack/blockstack-browser/issues/214: design launch modal

#### Bugs
- [x] https://github.com/blockstack/blockstack-browser/issues/566: profile list card pending is smaller than non-pending card
- [x] https://github.com/blockstack/blockstack-browser/issues/616: flex-box issue in safari

#### Pushed to [v0.13.0](https://github.com/blockstack/blockstack-browser/projects/11)
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/589: Add micro-interactions to home screen~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/602: update status bar to have navigation controls~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/513: add imagery of browser to readme.md~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/488: design installation window~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/183: add user's real name to profile card list on landing view~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/198: create a profile pending view~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/370: create design requirements for the registration process~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/521: Add an app version number in local storage~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/625: design photo upload page in profile editing section~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/641: add progress dots to on-boarding screens~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/570: build new "create profile" button in profiles app~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/635: Move profile list view below auto-generated profile~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/260: ui build of live search query view inside profiles app~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/262: ui build of edit profile pages inside the profiles app~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/261: design of edit profile pages inside the profiles app~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/259: design live search query view inside profiles app~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/258: live design new profiles app register pages~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/507: resolve issue with sidebar on storage app~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/542: Timeouts and Hangs on Auth Requests~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/628: Show more verbose registration errors on low balance~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/611: Daily name registration 7/11-7/14~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/574: Address generation logic should format address based on network~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/565: Notify users when their name is ready to be used~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/633: Create enter password modal/page component~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/526: Update browser to include core zero confirmation fixes~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/466: Review explorer profile card design~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/458: Address pull request into blockstack app generator~~

#### Bugs pushed to [v0.13.0](https://github.com/blockstack/blockstack-browser/projects/11)
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/638: spacing issue in wallet~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/395: Profile pictures shape~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/494: Profile image won't update when uploaded~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/631: Mixed-content blocking prevents usage of storage on apps deployed with https~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/629: Investigate max length of authentication responses~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/600: Error in sign in approval process~~

#### Backlogged
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/599: Run browser in native app window~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/573: Social proofs should marked untrusted unless verified~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/622: Click/Tap to verify identity key~~
