### ISSUE TITLE
v0.13.0 release overview

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#627]
Blockstack Browser prototype — https://invis.io/N2A7UM1X7

### Highlights
- n/a

#### Tasks
- [x] https://github.com/blockstack/blockstack-browser/issues/602: update status bar to have navigation controls
- [x] https://github.com/blockstack/blockstack-browser/issues/662: ui build of new status bar design
- [x] https://github.com/blockstack/blockstack-browser/issues/663: update beacon app icon on browser
- [ ] https://github.com/blockstack/blockstack-browser/issues/621: design new native macOS layout of browser
- [ ] https://github.com/blockstack/blockstack-browser/issues/589: Add micro-interactions to home screen
- [ ] https://github.com/blockstack/blockstack-browser/issues/513: add imagery of browser to readme.md
- [ ] https://github.com/blockstack/blockstack-browser/issues/198: create a profile pending view
- [ ] https://github.com/blockstack/blockstack-browser/issues/370: create design requirements for the registration process
- [ ] https://github.com/blockstack/blockstack-browser/issues/521: Add an app version number in local storage
- [ ] https://github.com/blockstack/blockstack-browser/issues/625: design photo upload page in profile editing section
- [ ] https://github.com/blockstack/blockstack-browser/issues/641: add progress dots to on-boarding screens
- [ ] https://github.com/blockstack/blockstack-browser/issues/570: build new "create profile" button in profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/635: Move profile list view below auto-generated profile
- [ ] https://github.com/blockstack/blockstack-browser/issues/260: ui build of live search query view inside profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/262: ui build of edit profile pages inside the profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/261: design of edit profile pages inside the profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/259: design live search query view inside profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/258: live design new profiles app register pages
- [ ] https://github.com/blockstack/blockstack-browser/issues/507: resolve issue with sidebar on storage app
- [ ] https://github.com/blockstack/blockstack-browser/issues/542: Timeouts and Hangs on Auth Requests
- [ ] https://github.com/blockstack/blockstack-browser/issues/628: Show more verbose registration errors on low balance
- [ ] https://github.com/blockstack/blockstack-browser/issues/574: Address generation logic should format address based on network
- [ ] https://github.com/blockstack/blockstack-browser/issues/565: Notify users when their name is ready to be used
- [ ] https://github.com/blockstack/blockstack-browser/issues/633: Create enter password modal/page component
- [ ] https://github.com/blockstack/blockstack-browser/issues/526: Update browser to include core zero confirmation fixes
- [ ] https://github.com/blockstack/blockstack-browser/issues/466: Review explorer profile card design
- [ ] https://github.com/blockstack/blockstack-browser/issues/458: Address pull request into blockstack app generator

#### Bugs
- [x] https://github.com/blockstack/blockstack-browser/issues/642: Status bar is clickable and scrollable when modal is open
- [ ] https://github.com/blockstack/blockstack-browser/issues/638: spacing issue in wallet
- [ ] https://github.com/blockstack/blockstack-browser/issues/395: Profile pictures shape
- [ ] https://github.com/blockstack/blockstack-browser/issues/494: Profile image won't update when uploaded
- [ ] https://github.com/blockstack/blockstack-browser/issues/631: Mixed-content blocking prevents usage of storage on apps deployed with https
- [ ] https://github.com/blockstack/blockstack-browser/issues/629: Investigate max length of authentication responses
- [ ] https://github.com/blockstack/blockstack-browser/issues/600: Error in sign in approval process
- [ ] https://github.com/blockstack/blockstack-browser/issues/572: Verify token error when profile goes from pending to registered
